import Head from "next/head";
import { type NextPageWithLayout } from "./_app";

// components import
import Navbar from "@/components/layouts/Navbar";
import TodoList from "@/components/TodoList";
import DefaultLayout from "@/components/layouts/DefaultLayout";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="min-h-screen pt-20 pb-14">
        <TodoList />
      </main>
    </>
  );
};

export default Home;

Home.getLayout = (page) => <DefaultLayout>{page}</DefaultLayout>;
