import { type NextPage } from "next";
import Head from "next/head";
import React from "react";

// components import
import Navbar from "@/components/Navbar";
import TodoList from "@/components/TodoList";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="min-h-screen pt-24 pb-14">
        <TodoList />
      </main>
    </>
  );
};

export default Home;
